import 'bootstrap/dist/css/bootstrap.min.css';
// import "../../public/sass/base/reset.scss";
import "../../public/sass/base/reset.scss";
import "../../public/sass/base/helper.scss";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from './componets/header';
import Footer from './componets/footer';
// import Header from "./components/header";
// import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Header />
      {children}
      <Footer/>
    </body>
    </html >
  );
}